name: delta_robot_ros2

services:
  ros-hamble-delta:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    working_dir: /workspace   
    # mem_limit: 4G  # выделение до 4 гигабайт памяти
    # cpus: 2.0  # ограничение до двух процессорных ядер     
    volumes:
      - ../:/workspace/src/delta_robot_ros2 
    env_file:
      - ./.env
    tty: true