<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find delta_robot_ros2)/urdf/common_macro.xacro"/>

  <xacro:property name="link_1_leg_length" value="0.4"/>
  <xacro:property name="link_2_leg_length" value="0.3"/>

<!-- *********************************************************************** -->
  <!-- Simple transmission -->
  <xacro:macro name="simple_transmission" params="joint_name">
      <transmission name="${joint_name}_transmission">
          <type>transmission_interface/SimpleTransmission</type>
          <joint name="${joint_name}">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          </joint>
          <actuator name="${joint_name}_actuator">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
          </actuator>
        </transmission>
  </xacro:macro>

  <xacro:macro name="leg" params="prefix origin_xyz origin_rpy">
  
    <!-- Параметры для шарнира, соединяющего основание и первое звено -->
    <joint name="${prefix}_joint_1" type="revolute">
      <origin xyz="${origin_xyz}" rpy="${origin_rpy}" />
      <parent link="base_link"/>
      <child link="${prefix}_link_1"/>
      <axis xyz="0 1 0"/>
      <limit lower="-${pi / 3}" upper="${pi / 3}" effort="1000" velocity="3"/>
    </joint>

    <xacro:simple_transmission joint_name="${prefix}_joint_1"/>

<!-- *********************************************************************** -->

    <!-- Первое звено -->
    <link name="${prefix}_link_1">
      <visual>
        <origin xyz="0 0 ${link_1_leg_length / 2}"/>
        <geometry>
          <cylinder length="${link_1_leg_length}" radius="0.05"/>
        </geometry>
         <material name="material_link_1">
          <color rgba="0 0 1 1"/>
        </material>
      </visual>
      <xacro:inertial_cylinder mass="1" length="${0.4}" radius="${0.05}"/>
    </link>

<!-- *********************************************************************** -->

    <!-- Сферический шарнир между первым и вторым звеном -->
    <joint name="${prefix}_joint_2" type="fixed">
      <origin xyz="0 0 ${link_1_leg_length}" rpy="0 0 0"/>
      <parent link="${prefix}_link_1"/>
      <child link="${prefix}_link_2"/>
      <axis xyz="1 0 0"/>
      <limit lower="-3.14" upper="3.14" effort="1000" velocity="3"/>
    </joint>

<!-- *********************************************************************** -->

    <!-- Второе звено -->
    <link name="${prefix}_link_2">
      <visual>
      <origin xyz="0 0 ${link_2_leg_length / 2}"/>
        <geometry>
          <cylinder length="${link_2_leg_length}" radius="0.05"/>
        </geometry>
        <material name="material_link_2">
          <color rgba="1 0 0 1"/>
        </material>
      </visual>
    </link>

<!-- *********************************************************************** -->

  </xacro:macro>

</robot>
