controller_manager:
  ros__parameters:
    update_rate: 55

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - leg_1_joint_1
      - leg_2_joint_1
      - leg_3_joint_1
    interface_name: position
    pid:
      leg_1_joint_1:
        p: 100.0
        i: 0.01
        d: 10.0
      leg_2_joint_1:
        p: 100.0
        i: 0.01
        d: 10.0
      leg_3_joint_1:
        p: 100.0
        i: 0.01
        d: 10.0