controllers:
  leg_1_joint_1_controller:
    type: joint_state_controller/JointStateController
    joint: leg_1_joint_1
    pid:
      p: 100.0
      i: 0.01
      d: 10.0

  leg_2_joint_1_controller:
    type: joint_state_controller/JointStateController
    joint: leg_2_joint_1
    pid:
      p: 100.0
      i: 0.01
      d: 10.0

  leg_3_joint_1_controller:
    type: joint_state_controller/JointStateController
    joint: leg_3_joint_1
    pid:
      p: 100.0
      i: 0.01
      d: 10.0
